// This file was generated by the TITAN Designer Eclipse plug-in version 8.1.0
// for (sajto@LAPTOP-E1TGO0KL)
// Copyright (c) 2000-2021 Ericsson Telecom AB

/**
 * <code>org.eclipse.titan.LaravelTestTTCN3.user_provided</code> package contains classes
 * that were written by the user, and contain the implementations of test ports and external functions, in the project LaravelTestTTCN3.
 *<p>
 * Do not edit this file unless you know what you are doing!
 */
package org.eclipse.titan.LaravelTestTTCN3.user_provided;

